### ISSUE TITLE
missing Requires: python(abi) >= 3.8

### ISSUE THREAD

**Issue by olafhering** [openSUSE/obs-service-cargo_vendor#19]
`obs-service-cargo_vendor-0.4.3~3` requires python 3.8+, but this requirement is not specified in the spec file. As a result this package fails to run in a SLE15-SP4 environment.

````
INFO:obs-service-cargo_vendor:Running OBS Source Service: obs-service-cargo_vendor
Traceback (most recent call last):
  File "/usr/lib/obs/service/cargo_vendor", line 213, in <module>
    main()
  File "/usr/lib/obs/service/cargo_vendor", line 208, in main
    if not do_cargo_vendor(args.srcdir, args.srctar, args.outdir, update, args.compression, args.tag):
  File "/usr/lib/obs/service/cargo_vendor", line 138, in do_cargo_vendor
    lsrcdir = shutil.copytree(srcdir, dirpath, dirs_exist_ok=True)
TypeError: copytree() got an unexpected keyword argument 'dirs_exist_ok'
````

**Comment by Firstyear** [comment]
@olafhering No problem I can fix that in the spec file.

**Comment by Firstyear** [comment]
https://build.opensuse.org/request/show/980940

**Comment by olafhering** [comment]
This is a runtime requires AFAICS.

**Comment by Firstyear** [comment]
BuildRequires implies the Requires IIRC

**Comment by Firstyear** [comment]
Okay, submitted new updates with Requires as well.
